# Generated by Django 3.2.8 on 2021-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
