# Generated by Django 3.2.8 on 2021-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allergies',
            field=models.IntegerField(choices=[(0, 'None'), (1, "Cow's milk"), (2, 'Eggs'), (3, 'Tree nuts'), (4, 'Peanuts'), (5, 'Shellfish'), (6, 'Wheat'), (7, 'Soy'), (8, 'Fish')], default=0),
        ),
    ]
