# Generated by Django 3.2.8 on 2021-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='allergies',
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
