# Generated by Django 3.2.9 on 2021-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_booking_booking_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_end',
            field=models.DateTimeField(null=True),
        ),
    ]
