# Generated by Django 3.2.8 on 2021-11-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['size']},
        ),
    ]
