# Generated by Django 3.2.9 on 2021-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_booking_booking_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='size',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='table',
            name='moveable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
