# Generated by Django 3.2.9 on 2021-12-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20211213_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
    ]
