# Generated by Django 3.2.8 on 2021-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
