# Generated by Django 3.2.8 on 2021-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
