# Generated by Django 3.2.9 on 2021-12-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_rename_number_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
