# Generated by Django 3.2.8 on 2021-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_intervals', models.PositiveIntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (30, '30 min')])),
                ('booking_duration', models.PositiveIntegerField()),
                ('auto_table_assign', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Booking detail',
                'verbose_name_plural': 'Booking details',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Opening hours',
                'verbose_name_plural': 'Opening hours',
                'ordering': ('weekday', 'from_time'),
                'unique_together': {('weekday', 'from_time', 'to_time')},
            },
        ),
    ]
