# Generated by Django 3.2.8 on 2021-11-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='booking_intervals',
        ),
    ]
