# Generated by Django 3.2.9 on 2021-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_bookingdetails_booking_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='auto_table_assign',
            field=models.IntegerField(choices=[(0, 'Off - admin assigns tables'), (1, 'Assign any tables in same zone'), (2, 'Assign any tables')]),
        ),
    ]
