# Generated by Django 3.2.9 on 2021-12-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_bookingdetails_auto_table_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdetails',
            old_name='auto_table_assign',
            new_name='table_assign_method',
        ),
    ]
