# Generated by Django 3.2.9 on 2021-12-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
