# Generated by Django 3.2.8 on 2021-10-26 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_reservation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to='auth.user'),
            preserve_default=False,
        ),
    ]
