# Generated by Django 3.2.8 on 2021-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'from_time'),
                'unique_together': {('weekday', 'from_time', 'to_time')},
            },
        ),
    ]
