# Generated by Django 3.2.8 on 2021-11-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.IntegerField(),
        ),
    ]
