# Generated by Django 3.2.8 on 2021-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_openinghours_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
