# Generated by Django 3.2.8 on 2021-11-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_booking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guests',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
