# Generated by Django 3.2.8 on 2021-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20211124_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_intervals_minutes', models.PositiveIntegerField(choices=[(5, 'Five'), (10, 'Ten'), (15, 'Fifteen'), (20, 'Thursday'), (30, 'Friday')])),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
