# Generated by Django 3.2.8 on 2021-11-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20211124_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guests',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_intervals_minutes',
            field=models.PositiveIntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (30, '30')]),
        ),
    ]
