# Generated by Django 3.2.8 on 2021-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_auto_20211124_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='booking_duration_minutes',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
