# Generated by Django 3.2.8 on 2021-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_bookingdetails_booking_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
