# Generated by Django 3.2.8 on 2021-11-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_booking_number_guests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
